#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#    Jun 08, 2022 12:30:34 AM BST  platform: Windows NT
#    Jun 08, 2022 12:38:28 AM BST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import IP_analyser

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = IP_analyser.Toplevel1(_top1)
    root.mainloop()

def print(*args):
    print('IP_analyser_support.print')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

def print(*args):
    print('IP_analyser_support.print')
    for arg in args:
        print ('another arg:', arg)
    sys.stdout.flush()

if __name__ == '__main__':
    IP_analyser.start_up()





