#############################################################################
# Generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
#  Jun 08, 2022 09:08:03 AM BST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    icons8_search_30_png "./icons8-search-30.png" 
    icons8_folder_30_png "./icons8-folder-30.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x451+520+407
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4612 1525
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map PC.TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map PC.TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                            Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }

                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd $top.pNo46 \
        -width 300 -height 200 -style "PC.TNotebook" -style PC.TNotebook 
    vTcl:DefineAlias "$top.pNo46" "PNotebook1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo46 configure -style "PC.TNotebook"
    bind $top.pNo46 <Button-1> {
        _button_press
    }
    bind $top.pNo46 <ButtonRelease-1> {
        _button_release
    }
    bind $top.pNo46 <Motion> {
        _mouse_over
    }
    frame $top.pNo46.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo46.t0" "PNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo46 add $top.pNo46.t0 \
        -padding 0 -sticky nsew -state normal -text {IP List} -image image6 \
        -compound left -underline -1 
    set site_4_0  $top.pNo46.t0
    label $site_4_0.lab47 \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Enter list of IP addresses or browse file} 
    vTcl:DefineAlias "$site_4_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.lab47
    text $site_4_0.tex49 \
        -background white -font TkTextFont -foreground black -height 364 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 264 -wrap word 
    $site_4_0.tex49 configure -font "TkTextFont"
    $site_4_0.tex49 insert end text
    vTcl:DefineAlias "$site_4_0.tex49" "Text1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.tex49
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) \
        -command {lambda _ : print(Text1.get("1.0",tk.END))} -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image icons8_search_30_png -padx 10 -pady 0 -text Analyse 
    vTcl:DefineAlias "$site_4_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.but50
    button $site_4_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image icons8_folder_30_png -padx 15 -pady 0 -text Browse 
    vTcl:DefineAlias "$site_4_0.but51" "Button2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_4_0.but51
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.033 -y 0 -rely 0.023 -width 0 \
        -relwidth 0.357 -height 0 -relheight 0.049 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tex49 \
        -in $site_4_0 -x 0 -relx 0.033 -y 0 -rely 0.093 -width 0 \
        -relwidth 0.44 -height 0 -relheight 0.847 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.617 -y 0 -rely 0.535 -width 127 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.617 -y 0 -rely 0.372 -width 127 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.pNo46.t1 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo46.t1" "PNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo46 add $top.pNo46.t1 \
        -padding 0 -sticky nsew -state normal -text VirusTotal -image image6 \
        -compound left -underline -1 
    set site_4_1  $top.pNo46.t1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_1.scr46 \
        -background $vTcl(actual_gui_bg) -height 407 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$site_4_1.scr46" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

        $base.pNo46.t1.scr46.01 configure -columns Col1 -height 4
        $base.pNo46.t1.scr46.01 configure -columns {Col1}
        $base.pNo46.t1.scr46.01 heading #0 -text {Tree}
        $base.pNo46.t1.scr46.01 heading #0 -anchor center
        $base.pNo46.t1.scr46.01 column #0 -width 280
        $base.pNo46.t1.scr46.01 column #0 -minwidth 20
        $base.pNo46.t1.scr46.01 column #0 -stretch 1
        $base.pNo46.t1.scr46.01 column #0 -anchor w
        $base.pNo46.t1.scr46.01 heading Col1 -text {Col1}
        $base.pNo46.t1.scr46.01 heading Col1 -anchor center
        $base.pNo46.t1.scr46.01 column Col1 -width 281
        $base.pNo46.t1.scr46.01 column Col1 -minwidth 20
        $base.pNo46.t1.scr46.01 column Col1 -stretch 1
        $base.pNo46.t1.scr46.01 column Col1 -anchor w
    place $site_4_1.scr46 \
        -in $site_4_1 -x 0 -relx 0.017 -y 0 -rely 0.023 -width 0 \
        -relwidth 0.967 -height 0 -relheight 0.947 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.pNo46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.007 -height 0 \
        -relheight 1.013 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

